image: elizabethdev/gitpod:infrastructure

tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'

vscode:
  extensions:
    - hashicorp.terraform
    - njzy.stats-bar
    - esbenp.prettier-vscode
